baseURL = "https://sewing-machine.github.io"

languageCode = 'en-us'
title = 'Усатый шьет'

theme = "PaperMod"

defaultContentLanguage = "ru"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[taxonomies]
  tag = "tags"

[params]
	env = "production"
    keywords = [
        "Усатый шьет",
        "Кастомный пошив из кордуры",
        ]
	yandexMetrika = "71539801"

[params.fuseOpts]
	isCaseSensitive = false
	shouldSort = true
	location = 0.0
	distance = 1000.0
	threshold = 0.4
	minMatchCharLength = 0.0
	keys = [
		"title",
		"permalink",
		"summary",
		"content"
	]

[menu]
    [[menu.main]]
        name = "Маркет"
        weight = -30
        identifier = "market"
        url = "/market/"
	[[menu.main]]
        name = "Поиск"
        identifier = "search"
        url = "/search/"
        weight = -10

enableRobotsTXT = true

